<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pos.DataTransfer\Pos.DataTransfer.csproj" />
    <ProjectReference Include="..\Proj.Util\Proj.Util.csproj" />
  </ItemGroup>

</Project>
